export const History = [
  {
    imageUrl: '',
    scientificName: 'ibuprofen',
    comment: '1 tab q8hr for 10 days Text',
    name: 'trufen 400 mg ',
    value :false,
    des:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    imageUrl: '',
    scientificName: 'ibuprofen',
    comment: '1 tab q8hr for 10 days Text',
    name: 'trufen 400 mg ',
    value :false,
    des:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    imageUrl: '',
    scientificName: 'ibuprofen',
    comment: '1 tab q8hr for 10 days Text',
    name: 'trufen 400 mg ',
    value :false,
    des:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    imageUrl: '',
    scientificName: 'ibuprofen',
    comment: '1 tab q8hr for 10 days Text',
    name: 'trufen 400 mg ',
    value :false,
    des:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    imageUrl: '',
    scientificName: 'ibuprofen',
    comment: '1 tab q8hr for 10 days Text',
    name: 'trufen 400 mg ',
    value :false,
    des:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
  {
    imageUrl: '',
    scientificName: 'ibuprofen',
    comment: '1 tab q8hr for 10 days Text',
    name: 'trufen 400 mg ',
    value :false,
    des:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, ecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
  },
];
