export default {
    BACKGROUD:require("../assets/bg.png"),
    LOCK:require("../assets/Lock.png"),
    LOGO:require("../assets/logo.png"),
    PHONE:require("../assets/phone.png"),
    DOCUSER:require("../assets/docuser.png"),
    EYE:require("../assets/Eye.png"),
    CEYE:require("../assets/ceye.png"),
    LIFTLINE:require("../assets/leftline.png"),
    RIGHTLINE:require("../assets/rightLine.png"),
    GOOGLE:require("../assets/google.png"),
    FB:require("../assets/fb.png"),
    TW:require("../assets/tw.png"),
    DOC:require("../assets/doc.png"),
    NEWSPAPER:require("../assets/newspaper.png"),
}